### ISSUE TITLE
Support node < 0.12.0?

### ISSUE THREAD

**Issue by rdmurphy** [rdmurphy/quaff#2]
`quaff` depends on [path.parse()](https://nodejs.org/api/path.html#path_path_parse_pathstring), which didn't get added to node until `0.12.0`.

Maybe this isn't an issue? I'm always bleeding edge when it comes to node, but I'm not sure if that'd burn others.

**Comment by dmil** [comment]
:+1: would prefer if it didn't
I'm on node `v0.10.26`

**Comment by rdmurphy** [comment]
Agreed. I'd like for it to be at least `0.10.*` compatible. Need to look into [path-parse](https://github.com/jbgutierrez/path-parse) polyfill and figure out a conditional install strategy for it. I'll see what I can do!

**Comment by rdmurphy** [comment]
@dmil Has been addressed with #4 and the release of `v1.1.0`! `quaff` now works with `node@v0.10.*`.

**Comment by dmil** [comment]
cool thanks!
